
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ABRE_COL ABRE_PAR ATE ATRIBUICAO COMENTARIO DESIGUALDADE DIVISAO DOIS_PONTOS ENTAO ESCREVA E_LOGICO FECHA_COL FECHA_PAR FIM FLUTUANTE ID IGUALDADE INTEIRO LEIA MAIOR MAIOR_IGUAL MENOR MENOR_IGUAL MULTIPLICACAO NEGACAO NUM_INTEIRO NUM_NOTACAO_CIENTIFICA NUM_PONTO_FLUTUANTE OU_LOGICO REPITA RETORNA SE SENAO SOMA SUBTRACAO VIRGULAnumero : NUM_INTEIRO\n                  | NUM_PONTO_FLUTUANTE\n                  | NUM_NOTACAO_CIENTIFICA'
    
_lr_action_items = {'NUM_INTEIRO':([0,],[2,]),'NUM_PONTO_FLUTUANTE':([0,],[3,]),'NUM_NOTACAO_CIENTIFICA':([0,],[4,]),'$end':([1,2,3,4,],[0,-1,-2,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'numero':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> numero","S'",1,None,None,None),
  ('numero -> NUM_INTEIRO','numero',1,'p_numero','tpp_parser.py',24),
  ('numero -> NUM_PONTO_FLUTUANTE','numero',1,'p_numero','tpp_parser.py',25),
  ('numero -> NUM_NOTACAO_CIENTIFICA','numero',1,'p_numero','tpp_parser.py',26),
]
