
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ABRE_COLCHETES ABRE_PARENTESES ADICAO ATE ATRIBUICAO COMENTARIO DIFERENTE DIVISAO DOIS_PONTOS E ENTAO ESCREVA FECHA_COLCHETES FECHA_PARENTESES FIM FLUTUANTE FLUTUANTE_LITERAL IDENTIFICADOR IGUAL INTEIRO INTEIRO_LITERAL LEIA MAIOR MAIOR_IGUAL MENOR MENOR_IGUAL MULTIPLICACAO NAO OU REPITA RETORNA SE SENAO SUBTRACAO VIRGULAfator : numeronumero : INTEIRO_LITERALnumero : FLUTUANTE_LITERAL'
    
_lr_action_items = {'INTEIRO_LITERAL':([0,],[3,]),'FLUTUANTE_LITERAL':([0,],[4,]),'$end':([1,2,3,4,],[0,-1,-2,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'fator':([0,],[1,]),'numero':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> fator","S'",1,None,None,None),
  ('fator -> numero','fator',1,'p_fator','parser2.py',21),
  ('numero -> INTEIRO_LITERAL','numero',1,'p_numero_1','parser2.py',26),
  ('numero -> FLUTUANTE_LITERAL','numero',1,'p_numero_2','parser2.py',32),
]
